задача 2
life-on-loan/Robots-master pull request #7
Opened 2022-04-17 12:54 UTC by life-on-loan

2022-04-17 18:23 UTC, vpyzhyanov commented
Почему не стали использовать паттерн "Фильтр"?

2022-04-17 18:25 UTC, vpyzhyanov requested changes

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    private FrameProperties prepareFrameProperties(JInternalFrame frame) {
Содержимое метода противоречит его названию и описанию. Описано для чего он это делает, но что на самом деле происходит не описано. Название метода (и JavaDoc) должно, в первую очередь, описывать что на самом деле происходит. Дополнительную информацию поместить в описание можно, но только в описание.

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    private FrameProperties prepareFrameProperties(JInternalFrame frame) {
А вообще подумайте, что будет если этого метода вообще не будет существовать?

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +            System.out.println(e.getMessage());
В серьёзных проектах такие штуки строжайшим образом запрещены, т.к. вместо этого используется подсистема логгирования. В этом проекте она тоже есть, используйте её. Исправив, обязательно напишите сюда почему нужно использовать именно её.

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/utils/FrameLoader.java
> +            throw new RuntimeException("Возникла ошибка при чтении состояния приложения из файла: " + e.getMessage());
Так себе идея. Попробуйте подумать почему.

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/utils/FrameSaver.java
> +    private final FileOutputStream fileOutputStream;
Частичная маленькая подсказка к вопросу про ООП. Обратите внимание, что это только частичная подсказка, помимо этого есть кое-что ещё.

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/utils/FrameSaver.java
> +            return objectWriter.writeValueAsString(properties);
Всякий раз, когда вижу однострочный метод у меня возникает вопрос "зачем?"

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/utils/FrameSaver.java
> +            throw new RuntimeException("Возникла ошибка при записи состояния приложения в файл: " + e.getMessage());
Много раз в коде вижу одно и то же. Повод задуматься

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/utils/FrameSaver.java
> +            throw new RuntimeException("Возникла ошибка при записи состояния приложения в файл: " + e.getMessage());
Неправильное формирование исключения. Нужно в конструктор, помимо текста сообщения, передать исходное исключение `e`. Обоснуйте зачем это нужно.

2022-04-17 18:25 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
>   * Следует разделить его на серию более простых методов (или вообще выделить отдельный класс).
Разве вы это ещё не сделали? Это можно было делать ещё в первой задаче. Но это не критично пока, можно сделать и в следующей задаче.

2022-04-17 18:54 UTC, vpyzhyanov commented on src/main/java/gui/FrameNames.java
> +            if (frameName.name.equals(frameNameToGet)) {
Замените на stream. Привыкайте использовать именно его, это будет вам гораздо полезнее. За одно воочию увидите паттерн "Фильтр".

2022-04-18 18:23 UTC, life-on-loan commented on src/main/java/gui/MainApplicationFrame.java
> +            System.out.println(e.getMessage());
Правильнее использовать подсистему логгирования, дабы любые сбои и предупреждения, возникающие по ходу работы, не были в консоли и не потерялись.

2022-04-20 14:47 UTC, vpyzhyanov requested changes

2022-04-20 14:47 UTC, vpyzhyanov commented on src/main/java/gui/FrameProperties.java
> +    public FrameProperties() {}
А этот конструктор почему публичный. А ещё тут не хватает комментария зачем он нужен.

2022-04-20 14:47 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        if (new File(FrameStateHandler.SAVED_STATE_PATH).exists()) {
А вот это критично. Всё ещё нарушено ООП. Всё ещё класс, который управляет интерфейсом приложения почему-то лезет в файлы. Эта проверка должна быть внутри метода `loadProperties()`
Почему это важно?! Если вы захотите хранить состояние окон в БД и измените только FrameStateHandler, то вся программа будет работать неправильно.

2022-04-20 14:47 UTC, vpyzhyanov commented on src/main/java/utils/FrameStateHandler.java
> +    public static final String SAVED_STATE_PATH = System.getProperty("user.home") + File.separator + "javaRobotsState.txt";
Разве кто-то должен знать об этой константе?

2022-04-20 14:47 UTC, vpyzhyanov commented on src/main/java/utils/FrameStateHandler.java
> +public class FrameStateHandler {
Отсутствует JavaDoc

2022-04-20 14:49 UTC, vpyzhyanov commented on src/main/java/utils/FrameLoader.java
> +            throw new RuntimeException("Возникла ошибка при чтении состояния приложения из файла: " + e.getMessage());
Забыли поговорить про это. Но не страшно, в новой версии кода, это уже неактуально.

2022-04-20 17:23 UTC, vpyzhyanov commented
Ставлю 8 баллов. Снизил за ООП. По git всё хорошо, 3 балла.

2022-04-24 09:16 UTC, vpyzhyanov requested changes

2022-04-24 09:16 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        if (frameStateHandler.isFileExisting()) {
Этот метод лишний. Вы исправили только использование константы, но логика осталась прежней. ООП как не было, так и нет. Стало чуть лучше, но не намного.

Ещё раз: класс для сохранения/восстановления состояния должен заниматься только сохранение и восстановлением состояния и больше ничем. Ни к чему классу MainApplicationFrame знать о существовании какого-то файла.

2022-04-24 09:16 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +    private JMenuBar generateMenuBar() {
под словами genarate обычно понимается использование некоторых случайных данных. Тут этого нет.

2022-04-24 09:16 UTC, vpyzhyanov commented on src/main/java/utils/FrameStateHandler.java
> +public class FrameStateHandler {
Акцент в описании совсем не на цели этого класса. Притом сама цель (предназначение) этого класса совсем отсутствует в описании. Плюс несогласованность названия класса и описания.

2022-04-24 09:16 UTC, vpyzhyanov commented on src/main/java/utils/FrameStateHandler.java
> +    public boolean isFileExisting() {
Инкапсуляция - прощай((( Рекомендую посмотреть материал по инкапсуляции, который я скидывал в нашем чате (последнее сообщение).

2022-04-25 02:59 UTC, vpyzhyanov requested changes

2022-04-25 02:59 UTC, vpyzhyanov commented on src/main/java/utils/FrameStateHandler.java
> +    private boolean isFileExisting = new File(SAVED_STATE_PATH).exists();
Зачем выносить это в поле класса? Оно используется всего один раз. Не увлекайтесь созданием классов, методов и полей, их не должно быть больше, чем необходимо. Как понять когда надо выделить новый метод? Если метод не помещается в один экран.

Кстати, с точки зрения английского языка нужно использовать глагол в такой форме: "exists", т.к. он обозначает продолжительность.

2022-04-25 02:59 UTC, vpyzhyanov commented on src/main/java/gui/MainApplicationFrame.java
> +        if (frameProperties.size() != 0) {
очевидно вы не тестировали свою программу. Словите NPE

2022-04-25 03:02 UTC, vpyzhyanov commented on src/main/java/gui/FrameProperties.java
> +    public FrameProperties() {}
можно было сделать его приватным

2022-04-25 03:03 UTC, vpyzhyanov commented on src/main/java/gui/FrameProperties.java
> +    public FrameProperties(FrameNames frameName, int x, int y, int width, int height, boolean isIcon, boolean isMaximum) {
Не исправлено

2022-04-25 03:07 UTC, vpyzhyanov commented
Вы баллы добрали, но они делятся на 2, поэтому добавлю только 1 балл. После исправления оставшихся небольших замечаний, можете мёрджить.

2022-04-26 14:38 UTC, merged